---
##
# Creates an AMI with Google PAM. This is done to allow secure ssh with two factor authentication.
#
# What it does:
#
# 1. Create new EC2 instance_type
# 2. Install/Update yum dependencies
##
- hosts: local
  connection: local
  
  vars_files:
    - "vault/aws-config.yml"
  
  roles:
    - role: aws-user

    - role: aws-launch
      playbook_group: "tmp_ami_group"
      ami_user: "{{ launch_user }}"
      user_data: "{{ launch_user_init_script }}"

- name: update all packages in a launched EC2 instance.
  hosts: tmp_ami_group
  become_user: root
  become: true
  roles:
    - role: aws-ami

# - name: setup PAM for 2FA authentication for every user
#   hosts: tmp_ami_group
#   gather_facts: no
#   roles:
#     - role: pam-user

# - name: setup configuration for ssh daemon for PAM only access
#   hosts: tmp_ami_group
#   gather_facts: no