---
- name: update sshd config to enable challenge responses
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^ChallengeResponseAuthentication
              line="ChallengeResponseAuthentication yes"
              state=present

- name: update sshd config to enable authentication methods for keyboard-interactive
  lineinfile: dest=/etc/ssh/sshd_config
              line="AuthenticationMethods publickey,keyboard-interactive:pam"
              insertafter=EOF
              state=present
              
- name: remove password based authentication from PAM configuration
  replace:  dest=/etc/pam.d/sshd
            regexp="^auth       substack     password-auth"
            replace="#auth       substack     password-auth"

- name: add google authenticator to PAM configuration as requirement
  lineinfile: dest=/etc/pam.d/sshd
              line="auth required pam_google_authenticator.so"
              insertafter=EOF
              state=present

- name: restart SSH
  shell: sleep 3; /etc/init.d/sshd restart
  async: 1
  poll: 0