# fail2ban version
fail2ban_version: 0.10.4

# Where should log outputs be sent to?
# SYSLOG, STDERR, STDOUT, file
fail2ban_logtarget: /var/log/secure

# The mode of sshd modes for filter
# normal (default), ddos, extra, or aggressive (combines all)
fail2ban_mode: aggressive

# How long in seconds should the ban last for?
# ex. 3600 seconds in an hour.
fail2ban_bantime: 3600

# How many times can they try before getting banned?
fail2ban_maxretry: 15

# How should the file changes be detected?
# gamin, polling, auto
fail2ban_backend: auto

# Which countries should be accepted?
# Countries should be separated by "|"
fail2ban_accept_country: US|United States