---
- name: ensure fail2ban is installed
  yum: fail2ban
    state: present
    enabled: yes

- name: ensure fail2ban is configured for jail
  template: 
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.local
  notify:
    - restart fail2ban

- name: ensure fail2ban is configured for iptable actions
  template: 
    src: iptables-multiport.conf.j2
    dest: /etc/fail2ban/action.d/iptables-multiport.local
  notify:
    - restart fail2ban

- name: ensure fail2ban starts on a fresh reboot
  service: 
    name: fail2ban 
    state: started 
    enabled: yes